services:
  gopherdis:
    image: ghcr.io/gosuda/gopherdis:latest
    container_name: gopherdis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - gopherdis-data:/data

volumes:
  gopherdis-data:
