package parser

import (
	"bytes"
	"strconv"
)


/* ----------------------------------------------------------------------------------------
 * A RESP parser for parsing replies returned by RM_Call or Lua's 'redis.call()'.
 *
 * The parser introduces callbacks that need to be set by the user. Each
 * callback represents a different reply type. Each callback gets a ctx that
 * was given to the ParseReply function. The callbacks also give the protocol
 * (underlying blob) of the current reply and the size.
 *
 * Some callbacks also get the parser object itself:
 * - ArrayCallback
 * - SetCallback
 * - MapCallback
 * - AttributeCallback
 *
 * These callbacks need to continue parsing by calling ParseReply a number of
 * times, according to the supplied length. Subsequent ParseReply calls may use
 * a different ctx, which will be used for nested CallReply objects.
 *
 * These callbacks also do not receive a proto_len, which is not known at the
 * time of parsing. Callers may calculate it themselves after parsing the
 * entire collection.
 *
 * NOTE: This parser is designed to only handle replies generated by Redis
 * itself. It does not perform many required validations and thus NOT SAFE FOR
 * PARSING USER INPUT.
 * ----------------------------------------------------------------------------------------
 */

// parseBulk parses bulk string replies ('$<len>\r\n<data>\r\n') or null bulk string ('$-1\r\n').
func (rp *ReplyParser) parseBulk(pCtx any) int {
	proto := rp.CurrLocation
	idx := FindCR(proto[1:])
	if idx < 0 {
		return C_ERR
	}
	idx++ // offset adjusted for proto[1:]

	bulkLen, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}

	rp.CurrLocation = proto[idx+2:] // skip \r\n

	if bulkLen == -1 {
		// Null bulk string ('$-1\r\n')
		protoLen := len(proto) - len(rp.CurrLocation)
		if rp.Callbacks.NullBulkStringCallback != nil {
			rp.Callbacks.NullBulkStringCallback(pCtx, proto[:protoLen])
		}
	} else {
		// Bulk string data with trailing \r\n
		if int64(len(rp.CurrLocation)) < bulkLen+2 {
			return C_ERR
		}
		str := rp.CurrLocation[:bulkLen]
		rp.CurrLocation = rp.CurrLocation[bulkLen+2:] // skip bulkLen and \r\n
		protoLen := len(proto) - len(rp.CurrLocation)
		if rp.Callbacks.BulkStringCallback != nil {
			rp.Callbacks.BulkStringCallback(pCtx, str, proto[:protoLen])
		}
	}

	return C_OK
}

// parseSimpleString parses simple string replies ('+<string>\r\n').
func (rp *ReplyParser) parseSimpleString(pCtx any) int {
	proto := rp.CurrLocation
	idx := FindCR(proto[1:])
	if idx < 0 {
		return C_ERR
	}
	idx++
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.SimpleStrCallback != nil {
		rp.Callbacks.SimpleStrCallback(pCtx, proto[1:idx], proto[:protoLen])
	}
	return C_OK
}

// parseError parses simple error replies ('-<error_message>\r\n').
func (rp *ReplyParser) parseError(pCtx any) int {
	proto := rp.CurrLocation
	idx := FindCR(proto[1:])
	if idx < 0 {
		return C_ERR
	}
	idx++
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.ErrorCallback != nil {
		rp.Callbacks.ErrorCallback(pCtx, proto[1:idx], proto[:protoLen])
	}
	return C_OK
}

// parseLong parses integer replies (':<number>\r\n').
func (rp *ReplyParser) parseLong(pCtx any) int {
	proto := rp.CurrLocation
	idx := FindCR(proto[1:])
	if idx < 0 {
		return C_ERR
	}
	idx++
	val, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.LongCallback != nil {
		rp.Callbacks.LongCallback(pCtx, val, proto[:protoLen])
	}
	return C_OK
}

// parseAttributes parses RESP3 attribute maps ('|<len>\r\n').
func (rp *ReplyParser) parseAttributes(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	length, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	if rp.Callbacks.AttributeCallback != nil {
		rp.Callbacks.AttributeCallback(rp, pCtx, length, proto)
	}
	return C_OK
}

// parseVerbatimString parses RESP3 verbatim strings ('=<len>\r\n<format>:<string>\r\n').
func (rp *ReplyParser) parseVerbatimString(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	bulkLen, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	if int64(len(rp.CurrLocation)) < bulkLen+2 {
		return C_ERR
	}
	formatAndStr := rp.CurrLocation[:bulkLen]
	rp.CurrLocation = rp.CurrLocation[bulkLen+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.VerbatimStringCallback != nil {
		var format, str []byte
		if bulkLen >= 4 {
			format = formatAndStr[:3] // 3 bytes format e.g. "txt"
			str = formatAndStr[4:]    // skip colon
		} else {
			str = formatAndStr
		}
		rp.Callbacks.VerbatimStringCallback(pCtx, format, str, proto[:protoLen])
	}
	return C_OK
}

// parseBigNumber parses RESP3 big number replies ('(<number>\r\n').
func (rp *ReplyParser) parseBigNumber(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.BigNumberCallback != nil {
		rp.Callbacks.BigNumberCallback(pCtx, proto[1:idx], proto[:protoLen])
	}
	return C_OK
}

// parseNull parses RESP3 null replies ('_\r\n').
func (rp *ReplyParser) parseNull(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.NullCallback != nil {
		rp.Callbacks.NullCallback(pCtx, proto[:protoLen])
	}
	return C_OK
}

// parseDouble parses RESP3 double replies (',<float>\r\n').
func (rp *ReplyParser) parseDouble(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	val, err := strconv.ParseFloat(string(proto[1:idx]), 64)
	if err != nil {
		val = 0
	}
	if rp.Callbacks.DoubleCallback != nil {
		rp.Callbacks.DoubleCallback(pCtx, val, proto[:protoLen])
	}
	return C_OK
}

// parseBool parses RESP3 boolean replies ('#t\r\n' or '#f\r\n').
func (rp *ReplyParser) parseBool(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	val := len(proto) > 1 && proto[1] == 't'
	rp.CurrLocation = proto[idx+2:]
	protoLen := len(proto) - len(rp.CurrLocation)
	if rp.Callbacks.BoolCallback != nil {
		rp.Callbacks.BoolCallback(pCtx, val, proto[:protoLen])
	}
	return C_OK
}

// parseArray parses array replies ('*<len>\r\n') or null array ('*-1\r\n').
func (rp *ReplyParser) parseArray(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	length, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	if length == -1 {
		protoLen := len(proto) - len(rp.CurrLocation)
		if rp.Callbacks.NullArrayCallback != nil {
			rp.Callbacks.NullArrayCallback(pCtx, proto[:protoLen])
		}
	} else {
		if rp.Callbacks.ArrayCallback != nil {
			rp.Callbacks.ArrayCallback(rp, pCtx, length, proto)
		}
	}
	return C_OK
}

// parseSet parses RESP3 set replies ('~<len>\r\n').
func (rp *ReplyParser) parseSet(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	length, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	if rp.Callbacks.SetCallback != nil {
		rp.Callbacks.SetCallback(rp, pCtx, length, proto)
	}
	return C_OK
}

// parseMap parses RESP3 map replies ('%<len>\r\n').
func (rp *ReplyParser) parseMap(pCtx any) int {
	proto := rp.CurrLocation
	idx := bytes.IndexByte(proto[1:], '\r')
	if idx < 0 {
		return C_ERR
	}
	idx++
	length, err := strconv.ParseInt(string(proto[1:idx]), 10, 64)
	if err != nil {
		return C_ERR
	}
	rp.CurrLocation = proto[idx+2:]
	if rp.Callbacks.MapCallback != nil {
		rp.Callbacks.MapCallback(rp, pCtx, length, proto)
	}
	return C_OK
}

// ParseReply parses the RESP reply starting at rp.CurrLocation.
// It detects the reply type prefix byte and delegates to the corresponding parser method.
// Returns C_OK on success or C_ERR on failure.
func (rp *ReplyParser) ParseReply(pCtx any) int {
	if len(rp.CurrLocation) == 0 {
		if rp.Callbacks.Error != nil {
			rp.Callbacks.Error(pCtx)
		}
		return C_ERR
	}

	switch rp.CurrLocation[0] {
	case '$':
		return rp.parseBulk(pCtx)
	case '+':
		return rp.parseSimpleString(pCtx)
	case '-':
		return rp.parseError(pCtx)
	case ':':
		return rp.parseLong(pCtx)
	case '*':
		return rp.parseArray(pCtx)
	case '~':
		return rp.parseSet(pCtx)
	case '%':
		return rp.parseMap(pCtx)
	case '#':
		return rp.parseBool(pCtx)
	case ',':
		return rp.parseDouble(pCtx)
	case '_':
		return rp.parseNull(pCtx)
	case '(':
		return rp.parseBigNumber(pCtx)
	case '=':
		return rp.parseVerbatimString(pCtx)
	case '|':
		return rp.parseAttributes(pCtx)
	default:
		if rp.Callbacks.Error != nil {
			rp.Callbacks.Error(pCtx)
		}
		return C_ERR
	}
}


